// CRM module configuration: drives the generic CRUD page (CrmModule.jsx).
// Every module stored by the backend lives in a `crm_*` collection.

export const AUDIT_CRITERIA = [
  { key: "founder_team", label: "Founder & Team", max: 10 },
  { key: "problem_validation", label: "Problem Validation", max: 10 },
  { key: "technology_product", label: "Technology & Product", max: 15 },
  { key: "market", label: "Market", max: 10 },
  { key: "business_model", label: "Business Model", max: 10 },
  { key: "traction", label: "Traction", max: 15 },
  { key: "financial", label: "Financial", max: 10 },
  { key: "ip_legal", label: "IP & Legal", max: 10 },
  { key: "funding", label: "Funding", max: 5 },
  { key: "engagement", label: "Incubein Engagement", max: 5 },
];

export const STAGE_OPTIONS = [
  "Ideation",
  "Prototype",
  "MVP/Pre-Revenue",
  "Revenue",
  "Growth/Scaling",
  "Seed Stage",
];

export const RAG_ORDER = { GREEN: 0, AMBER: 1, RED: 2 };

const OWNERS = ["Incubation Manager", "Manager Innovation", "Technical Assistant", "CEO"];

const YES_NO = ["Yes", "No"];

const MODULE_CONFIGS = {
  startups: {
    label: "Startups",
    singular: "Startup",
    defaults: { status: "Active", record_status: "Active", crm_owner: "Incubation Manager" },
    filters: ["stage", "status", "sector", "priority"],
    columns: [
      { key: "code", label: "Code", kind: "text" },
      { key: "name", label: "Name", kind: "text", main: true },
      { key: "sector", label: "Sector", kind: "text" },
      { key: "stage", label: "Stage", kind: "stage" },
      { key: "status", label: "Status", kind: "pill" },
      { key: "health_band", label: "Health", kind: "health" },
      { key: "priority", label: "Priority", kind: "pill" },
      { key: "city", label: "City", kind: "text" },
    ],
    fields: [
      { key: "name", label: "Startup Name", type: "text" },
      { key: "code", label: "Code (auto)", type: "text" },
      { key: "previous_name", label: "Previous Name", type: "text" },
      { key: "startup_type", label: "Startup Type", type: "text" },
      { key: "program", label: "Program", type: "select", options: ["Seed Stage", "MVP/Pre-Revenue", "Acceleration"] },
      { key: "stage", label: "Stage", type: "select", options: STAGE_OPTIONS },
      { key: "entry_route", label: "Entry Route", type: "select", options: ["Application", "Referral", "Campus", "Hackathon", "Walk-in"] },
      { key: "status", label: "Status", type: "select", options: ["Active", "Graduated", "Dropped", "On Hold"] },
      { key: "priority", label: "Priority", type: "select", options: ["High", "Medium", "Low"] },
      { key: "application_date", label: "Application Date", type: "date" },
      { key: "selection_date", label: "Selection Date", type: "date" },
      { key: "incubation_start", label: "Incubation Start", type: "date" },
      { key: "graduation_date", label: "Graduation Date", type: "date" },
      { key: "sector", label: "Sector", type: "text" },
      { key: "business_model", label: "Business Model", type: "select", options: ["B2B", "B2C", "B2B2C", "C2C", "Marketplace", "D2C"] },
      { key: "geography", label: "Geography", type: "text" },
      { key: "state", label: "State", type: "text" },
      { key: "district", label: "District", type: "text" },
      { key: "city", label: "City", type: "text" },
      { key: "website", label: "Website", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "crm_owner", label: "CRM Owner", type: "select", options: OWNERS },
      { key: "relationship_manager", label: "Relationship Manager", type: "select", options: OWNERS },
      { key: "primary_mentor", label: "Primary Mentor", type: "text" },
      { key: "source_college", label: "Source College", type: "text" },
      { key: "record_status", label: "Record Status", type: "select", options: ["Active", "Inactive", "Archived"] },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  founders: {
    label: "Founders & Team",
    singular: "Founder",
    defaults: {},
    filters: ["founder_type", "role", "student_status", "gender"],
    columns: [
      { key: "name", label: "Name", kind: "text", main: true },
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "role", label: "Role", kind: "text" },
      { key: "founder_type", label: "Type", kind: "pill" },
      { key: "student_status", label: "Student", kind: "pill" },
      { key: "institution", label: "Institution", kind: "text" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "name", label: "Full Name", type: "text" },
      { key: "founder_type", label: "Founder Type", type: "select", options: ["Founder", "Co-Founder", "Team Member"] },
      { key: "role", label: "Role", type: "text" },
      { key: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { key: "age_group", label: "Age Group", type: "select", options: ["Under 25", "25-34", "35-44", "45+"] },
      { key: "student_status", label: "Student Status", type: "select", options: ["Student", "Alumnus", "Non-student"] },
      { key: "institution", label: "Institution", type: "text" },
      { key: "department", label: "Department", type: "text" },
      { key: "qualification", label: "Qualification", type: "text" },
      { key: "discipline", label: "Discipline", type: "text" },
      { key: "commitment", label: "Commitment", type: "select", options: ["Full-time", "Part-time", "Advisor"] },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "linkedin", label: "LinkedIn", type: "text" },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  audits: {
    label: "Startup Audits",
    singular: "Audit",
    defaults: {},
    filters: ["audit_type", "band", "ceo_decision"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text", main: true },
      { key: "audit_type", label: "Type", kind: "text" },
      { key: "audit_date", label: "Date", kind: "date" },
      { key: "total_score", label: "Score", kind: "score" },
      { key: "band", label: "Band", kind: "health" },
      { key: "ceo_decision", label: "Decision", kind: "pill" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "audit_type", label: "Audit Type", type: "select", options: ["Entry Audit", "Quarterly Review", "Annual Review", "Graduation Audit"] },
      { key: "audit_date", label: "Audit Date", type: "date" },
      { key: "auditor", label: "Auditor", type: "select", options: OWNERS },
      ...AUDIT_CRITERIA.map((c) => ({ key: c.key, label: `${c.label} (/${c.max})`, type: "number" })),
      { key: "strengths", label: "Strengths", type: "textarea" },
      { key: "gaps", label: "Gaps", type: "textarea" },
      { key: "ceo_decision", label: "CEO Decision", type: "select", options: ["Continue Support", "Intensify Support", "Graduate", "Wind Down", "Facilitate Exit"] },
      { key: "next_review", label: "Next Review", type: "date" },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  milestones: {
    label: "Milestones",
    singular: "Milestone",
    defaults: { status: "In Progress", owner: "Incubation Manager" },
    filters: ["status", "owner"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "milestone", label: "Milestone", kind: "text", main: true },
      { key: "status", label: "Status", kind: "pill" },
      { key: "target_date", label: "Target", kind: "date" },
      { key: "actual_date", label: "Actual", kind: "date" },
      { key: "owner", label: "Owner", kind: "text" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "milestone", label: "Milestone", type: "text" },
      { key: "milestone_type", label: "Milestone Type", type: "select", options: ["MVP", "IP Filing", "First Revenue", "Product-Market Fit", "Grant Received", "Rs 1 Lakh Revenue", "Pilot Signed", "Funding Milestone", "Other"] },
      { key: "status", label: "Status", type: "select", options: ["Not Started", "In Progress", "Completed", "Achieved", "Delayed", "Blocked", "Cancelled"] },
      { key: "priority", label: "Priority", type: "select", options: ["P1 Critical", "P2 High", "P3 Medium", "P4 Low"] },
      { key: "target_date", label: "Target Date", type: "date" },
      { key: "actual_date", label: "Actual Date", type: "date" },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
      { key: "target_metric", label: "Target Metric", type: "text" },
      { key: "evidence", label: "Evidence", type: "text" },
      { key: "verified_by", label: "Verified By", type: "text" },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  actions: {
    label: "90-Day Action Tracker",
    singular: "Action",
    defaults: { status: "Not Started", owner: "Incubation Manager", source: "Audit" },
    filters: ["status", "priority", "rag", "owner"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "action", label: "Action", kind: "text", main: true },
      { key: "owner", label: "Owner", kind: "text" },
      { key: "priority", label: "Priority", kind: "pill" },
      { key: "deadline", label: "Deadline", kind: "date" },
      { key: "rag", label: "RAG", kind: "rag" },
      { key: "status", label: "Status", kind: "pill" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "source", label: "Source", type: "select", options: ["Audit", "Mentor", "Review", "Incubation Manager", "CEO Office"] },
      { key: "action", label: "Action", type: "text" },
      { key: "kpi", label: "KPI", type: "text" },
      { key: "baseline", label: "Baseline", type: "number" },
      { key: "target", label: "Target", type: "number" },
      { key: "actual", label: "Actual", type: "number" },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
      { key: "priority", label: "Priority", type: "select", options: ["P1 Critical", "P2 High", "P3 Medium", "P4 Low"] },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "deadline", label: "Deadline", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Not Started", "In Progress", "Completed", "Delayed", "Blocked", "Achieved"] },
      { key: "completion_date", label: "Completion Date", type: "date" },
      { key: "ceo_remark", label: "CEO Remark", type: "textarea" },
    ],
  },

  risks: {
    label: "Risk Register",
    singular: "Risk",
    defaults: { status: "Open", owner: "Incubation Manager" },
    filters: ["category", "status", "risk_level", "owner"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "risk", label: "Risk", kind: "text", main: true },
      { key: "category", label: "Category", kind: "pill" },
      { key: "probability", label: "Prob.", kind: "number" },
      { key: "impact", label: "Impact", kind: "number" },
      { key: "risk_score", label: "Score", kind: "number" },
      { key: "risk_level", label: "Level", kind: "risk" },
      { key: "status", label: "Status", kind: "pill" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "category", label: "Category", type: "select", options: ["Market", "Technical", "Financial", "Regulatory", "Team", "Operational", "Legal"] },
      { key: "risk", label: "Risk", type: "text" },
      { key: "probability", label: "Probability (1-5)", type: "number" },
      { key: "impact", label: "Impact (1-5)", type: "number" },
      { key: "mitigation", label: "Mitigation", type: "textarea" },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
      { key: "target_date", label: "Target Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Open", "Monitoring", "Mitigating", "Closed"] },
      { key: "residual_risk", label: "Residual Risk", type: "select", options: ["Low", "Medium", "High", "Critical"] },
      { key: "last_reviewed", label: "Last Reviewed", type: "date" },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  customers: {
    label: "Customer CRM",
    singular: "Customer",
    defaults: { owner: "Incubation Manager" },
    filters: ["customer_type", "lead_status", "customer_status"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "name", label: "Customer", kind: "text", main: true },
      { key: "customer_type", label: "Type", kind: "pill" },
      { key: "lead_status", label: "Lead Status", kind: "pill" },
      { key: "customer_status", label: "Status", kind: "pill" },
      { key: "revenue", label: "Revenue", kind: "money" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "name", label: "Customer Name", type: "text" },
      { key: "customer_type", label: "Type", type: "select", options: ["B2B", "B2C", "Government", "Institutional"] },
      { key: "geography", label: "Geography", type: "text" },
      { key: "lead_source", label: "Lead Source", type: "text" },
      { key: "lead_status", label: "Lead Status", type: "select", options: ["New", "Contacted", "Qualified Lead", "Proposal", "Won", "Lost"] },
      { key: "customer_status", label: "Customer Status", type: "select", options: ["Prospect", "Customer", "Churned"] },
      { key: "first_contact", label: "First Contact", type: "date" },
      { key: "first_purchase", label: "First Purchase", type: "date" },
      { key: "revenue", label: "Revenue (INR)", type: "money" },
      { key: "repeat_customer", label: "Repeat Customer", type: "select", options: YES_NO },
      { key: "contract_value", label: "Contract Value", type: "money" },
      { key: "renewal_date", label: "Renewal Date", type: "date" },
      { key: "nps", label: "NPS (0-10)", type: "number" },
      { key: "feedback", label: "Feedback", type: "textarea" },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
    ],
  },

  deals: {
    label: "Sales Pipeline",
    singular: "Deal",
    defaults: { deal_status: "Open", sales_owner: "Incubation Manager" },
    filters: ["sales_stage", "deal_status", "sales_owner"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "deal_name", label: "Deal", kind: "text", main: true },
      { key: "sales_stage", label: "Stage", kind: "pill" },
      { key: "pipeline_value", label: "Value", kind: "money" },
      { key: "expected_close", label: "Expected Close", kind: "date" },
      { key: "deal_status", label: "Status", kind: "pill" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "deal_name", label: "Deal Name", type: "text" },
      { key: "sales_stage", label: "Stage", type: "select", options: ["Discovery", "Demo", "Proposal", "Negotiation", "Closing", "Won", "Lost"] },
      { key: "pipeline_value", label: "Pipeline Value (INR)", type: "money" },
      { key: "expected_close", label: "Expected Close", type: "date" },
      { key: "actual_close", label: "Actual Close", type: "date" },
      { key: "deal_status", label: "Status", type: "select", options: ["Open", "Won", "Lost"] },
      { key: "sales_owner", label: "Sales Owner", type: "select", options: OWNERS },
      { key: "next_action", label: "Next Action", type: "text" },
      { key: "next_action_date", label: "Next Action Date", type: "date" },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  financials: {
    label: "Financial KPI",
    singular: "Financial Record",
    defaults: { owner: "Incubation Manager", fy: "FY 2026-27" },
    filters: ["fy", "month", "statements"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "month", label: "Month", kind: "text" },
      { key: "month_end", label: "Month End", kind: "date" },
      { key: "revenue", label: "Revenue", kind: "money" },
      { key: "mrr", label: "MRR", kind: "money" },
      { key: "expenses", label: "Expenses", kind: "money" },
      { key: "cash_balance", label: "Cash", kind: "money" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "fy", label: "Financial Year", type: "text" },
      { key: "month", label: "Month", type: "select", options: ["April", "May", "June", "July", "August", "September", "October", "November", "December", "January", "February", "March"] },
      { key: "month_end", label: "Month End Date", type: "date" },
      { key: "revenue", label: "Revenue (INR)", type: "money" },
      { key: "mrr", label: "MRR (INR)", type: "money" },
      { key: "cogs", label: "COGS (INR)", type: "money" },
      { key: "expenses", label: "Expenses (INR)", type: "money" },
      { key: "cash_balance", label: "Cash Balance (INR)", type: "money" },
      { key: "team_size", label: "Team Size", type: "number" },
      { key: "jobs_created", label: "Jobs Created", type: "number" },
      { key: "gst_paid", label: "GST Paid (INR)", type: "money" },
      { key: "statements", label: "Statements", type: "select", options: ["Submitted", "Pending", "N/A"] },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  funding: {
    label: "Funding Tracker",
    singular: "Funding Record",
    defaults: { owner: "Incubation Manager", status: "Applied" },
    filters: ["stage", "source", "status"],
    columns: [
      { key: "startup_name", label: "Startup", kind: "text" },
      { key: "scheme", label: "Scheme", kind: "text", main: true },
      { key: "stage", label: "Stage", kind: "pill" },
      { key: "source", label: "Source", kind: "text" },
      { key: "amount_sought", label: "Sought", kind: "money" },
      { key: "amount_received", label: "Received", kind: "money" },
      { key: "status", label: "Status", kind: "pill" },
    ],
    fields: [
      { key: "startup_id", label: "Startup", type: "ref", ref: "startups" },
      { key: "stage", label: "Funding Stage", type: "select", options: ["Pre-Seed", "Seed", "Series A", "Series B", "Grant", "Debt"] },
      { key: "source", label: "Source", type: "select", options: ["Mahamission Startup Fund", "GEM Funding", "CSI Scheme", "BIRAC", "AVISHKAR Scheme", "SSIP Grant", "Private VC", "Angel"] },
      { key: "scheme", label: "Scheme / Programme", type: "text" },
      { key: "readiness", label: "Readiness", type: "select", options: ["Early", "Investment Ready", "Diligence", "Term Sheet"] },
      { key: "amount_sought", label: "Amount Sought (INR)", type: "money" },
      { key: "amount_received", label: "Amount Received (INR)", type: "money" },
      { key: "equity_offered", label: "Equity Offered (%)", type: "number" },
      { key: "valuation", label: "Valuation (INR)", type: "money" },
      { key: "application_date", label: "Application Date", type: "date" },
      { key: "decision_date", label: "Decision Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Applied", "In Discussion", "In Negotiation", "Partial", "Approved", "Received", "Declined"] },
      { key: "investor", label: "Investor", type: "text" },
      { key: "next_action", label: "Next Action", type: "text" },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
      { key: "deadline", label: "Deadline", type: "date" },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  colleges: {
    label: "Colleges",
    singular: "College",
    defaults: { status: "Active", owner: "Manager Innovation" },
    filters: ["district", "college_type", "mou", "status"],
    columns: [
      { key: "code", label: "Code", kind: "text" },
      { key: "name", label: "College", kind: "text", main: true },
      { key: "district", label: "District", kind: "text" },
      { key: "college_type", label: "Type", kind: "pill" },
      { key: "mou", label: "MoU", kind: "pill" },
      { key: "status", label: "Status", kind: "pill" },
      { key: "students_reached", label: "Students", kind: "number" },
      { key: "ideas_generated", label: "Ideas", kind: "number" },
      { key: "referrals_count", label: "Referrals", kind: "number" },
    ],
    fields: [
      { key: "code", label: "Code (auto)", type: "text" },
      { key: "name", label: "College Name", type: "text" },
      { key: "district", label: "District", type: "text" },
      { key: "taluka", label: "Taluka", type: "text" },
      { key: "college_type", label: "Type", type: "select", options: ["Engineering", "Science", "Commerce", "Management", "Arts", "Agriculture", "Pharmacy"] },
      { key: "principal", label: "Principal", type: "text" },
      { key: "coordinator", label: "Coordinator", type: "text" },
      { key: "coordinator_contact", label: "Coordinator Contact", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "startup_cell", label: "Startup Cell", type: "select", options: YES_NO },
      { key: "first_contact", label: "First Contact", type: "date" },
      { key: "last_visit", label: "Last Visit", type: "date" },
      { key: "next_visit", label: "Next Visit", type: "date" },
      { key: "students_reached", label: "Students Reached", type: "number" },
      { key: "ideas_generated", label: "Ideas Generated", type: "number" },
      { key: "ideas_screened", label: "Ideas Screened", type: "number" },
      { key: "referrals", label: "Referrals", type: "number" },
      { key: "mou", label: "MoU Status", type: "select", options: ["Draft", "In Process", "Signed", "Active", "Expired"] },
      { key: "mou_date", label: "MoU Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },

  students: {
    label: "Student Pipeline",
    singular: "Student",
    defaults: { owner: "Manager Innovation", year: "Final Year", referral: "No", startup_created: "No" },
    filters: ["stage", "sector", "referral", "startup_created"],
    columns: [
      { key: "code", label: "Code", kind: "text" },
      { key: "student_name", label: "Student", kind: "text", main: true },
      { key: "college_name", label: "College", kind: "text" },
      { key: "course", label: "Course", kind: "text" },
      { key: "idea", label: "Idea", kind: "text" },
      { key: "sector", label: "Sector", kind: "text" },
      { key: "stage", label: "Stage", kind: "stage" },
      { key: "referral", label: "Referred", kind: "pill" },
      { key: "startup_created", label: "Startup", kind: "pill" },
    ],
    fields: [
      { key: "code", label: "Code (auto)", type: "text" },
      { key: "college_id", label: "College", type: "ref", ref: "colleges" },
      { key: "student_name", label: "Student Name", type: "text" },
      { key: "course", label: "Course", type: "text" },
      { key: "year", label: "Year", type: "select", options: ["First Year", "Second Year", "Third Year", "Final Year", "Alumnus"] },
      { key: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "idea", label: "Idea", type: "text" },
      { key: "sector", label: "Sector", type: "text" },
      { key: "problem", label: "Problem", type: "text" },
      { key: "mentor", label: "Mentor", type: "text" },
      { key: "stage", label: "Stage", type: "select", options: STAGE_OPTIONS },
      { key: "validation", label: "Validation", type: "text" },
      { key: "prototype", label: "Prototype", type: "select", options: YES_NO },
      { key: "referral", label: "Referred to Incubation", type: "select", options: YES_NO },
      { key: "referral_date", label: "Referral Date", type: "date" },
      { key: "startup_created", label: "Startup Created", type: "select", options: YES_NO },
      { key: "owner", label: "Owner", type: "select", options: OWNERS },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
};

export function getModuleConfig(module) {
  return MODULE_CONFIGS[module] || null;
}

export const MODULE_IDS = Object.keys(MODULE_CONFIGS);