"""batch_8_outreach_and_scheduled_meetings

Revision ID: 56b1fd2aeaf2
Revises: c6227352dded
Create Date: 2026-07-23 14:37:39.048949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b1fd2aeaf2'
down_revision: Union[str, Sequence[str], None] = 'c6227352dded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_leads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incubator_id', sa.String(length=255), nullable=True),
    sa.Column('incubator_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Draft'"), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('reply_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intent_classification', sa.String(length=100), nullable=True),
    sa.Column('lead_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('meeting_link', sa.String(length=2048), nullable=True),
    sa.Column('meeting_scheduled_at', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('contact_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_contact_reason', sa.String(length=255), server_default=sa.text("'None'"), nullable=False),
    sa.Column('followup_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_sentiment', sa.String(length=100), nullable=True),
    sa.Column('reply_urgency', sa.String(length=50), nullable=True),
    sa.Column('reply_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outreach_leads_email', 'outreach_leads', ['email'], unique=False)
    op.create_index('ix_outreach_leads_email_incubator_name', 'outreach_leads', ['email', 'incubator_name'], unique=False)
    op.create_index('ix_outreach_leads_incubator_id', 'outreach_leads', ['incubator_id'], unique=False)
    op.create_index('ix_outreach_leads_last_followup_at', 'outreach_leads', ['last_followup_at'], unique=False)
    op.create_index('ix_outreach_leads_sent_at', 'outreach_leads', ['sent_at'], unique=False)
    op.create_index('ix_outreach_leads_status', 'outreach_leads', ['status'], unique=False)
    op.create_table('scheduled_meetings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('incubator_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Scheduled'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['outreach_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', name='uq_scheduled_meetings_lead_id')
    )
    op.create_index('ix_scheduled_meetings_calendar_event_id', 'scheduled_meetings', ['calendar_event_id'], unique=False)
    op.create_index('ix_scheduled_meetings_date', 'scheduled_meetings', ['date'], unique=False)
    op.create_index('ix_scheduled_meetings_status', 'scheduled_meetings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_meetings_status', table_name='scheduled_meetings')
    op.drop_index('ix_scheduled_meetings_date', table_name='scheduled_meetings')
    op.drop_index('ix_scheduled_meetings_calendar_event_id', table_name='scheduled_meetings')
    op.drop_table('scheduled_meetings')
    op.drop_index('ix_outreach_leads_status', table_name='outreach_leads')
    op.drop_index('ix_outreach_leads_sent_at', table_name='outreach_leads')
    op.drop_index('ix_outreach_leads_last_followup_at', table_name='outreach_leads')
    op.drop_index('ix_outreach_leads_incubator_id', table_name='outreach_leads')
    op.drop_index('ix_outreach_leads_email_incubator_name', table_name='outreach_leads')
    op.drop_index('ix_outreach_leads_email', table_name='outreach_leads')
    op.drop_table('outreach_leads')
    # ### end Alembic commands ###
