"""initial_postgresql_schema

Revision ID: c6227352dded
Revises: 
Create Date: 2026-07-22 23:13:53.352312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6227352dded'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('investment_stage', sa.String(length=255), nullable=True),
    sa.Column('investment_focus', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_investors_slug')
    )
    op.create_index('ix_investors_is_active', 'investors', ['is_active'], unique=False)
    op.create_index('ix_investors_name', 'investors', ['name'], unique=False)
    op.create_index('ix_investors_organization', 'investors', ['organization'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('Incubator', 'Investor', 'Mentor', 'Sector', 'Startup', name='relationship_source_type_enum'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('BELONGS_TO_SECTOR', 'FUNDED', 'HAS_MENTOR', 'INCUBATED', name='relationship_type_enum'), nullable=False),
    sa.Column('target_type', sa.Enum('Incubator', 'Investor', 'Mentor', 'Sector', 'Startup', name='relationship_target_type_enum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_value', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(target_id IS NOT NULL AND target_value IS NULL) OR (target_id IS NULL AND target_value IS NOT NULL)', name='ck_relationships_exactly_one_target'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relationships_relationship_type', 'relationships', ['relationship_type'], unique=False)
    op.create_index('ix_relationships_source_type_source_id', 'relationships', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_relationships_target_type_target_id', 'relationships', ['target_type', 'target_id'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'code', name='uq_states_country_code_code'),
    sa.UniqueConstraint('country_code', 'name', name='uq_states_country_code_name')
    )
    op.create_index('ix_states_code', 'states', ['code'], unique=False)
    op.create_index('ix_states_name', 'states', ['name'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'name', name='uq_cities_state_id_name')
    )
    op.create_index('ix_cities_name', 'cities', ['name'], unique=False)
    op.create_index('ix_cities_state_id', 'cities', ['state_id'], unique=False)
    op.create_table('incubators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('organization_type', sa.Enum('Academic', 'Academic Collab Partner', 'Academic Institutions', 'Corporate', 'Government', 'Government Support', 'Private', 'University', name='organization_type_enum'), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('founded_year BETWEEN 1800 AND 2026', name='ck_incubators_founded_year'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_incubators_slug')
    )
    op.create_index('ix_incubators_city_id', 'incubators', ['city_id'], unique=False)
    op.create_index('ix_incubators_is_active', 'incubators', ['is_active'], unique=False)
    op.create_index('ix_incubators_name', 'incubators', ['name'], unique=False)
    op.create_index('ix_incubators_slug', 'incubators', ['slug'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incubator_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incubator_id'], ['incubators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_mentors_slug')
    )
    op.create_index('ix_mentors_full_name', 'mentors', ['full_name'], unique=False)
    op.create_index('ix_mentors_incubator_id', 'mentors', ['incubator_id'], unique=False)
    op.create_index('ix_mentors_is_active', 'mentors', ['is_active'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incubator_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('funding_stage', sa.Enum('Unknown', 'Seed', 'Series B', 'Series C', 'Series D', 'Series E', 'Series F', 'IPO', 'Post-IPO', 'Closed', 'Dead', name='funding_stage_enum'), server_default='Unknown', nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('founded_year BETWEEN 1800 AND 2026', name='ck_startups_founded_year'),
    sa.ForeignKeyConstraint(['incubator_id'], ['incubators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_startups_slug')
    )
    op.create_index('ix_startups_funding_stage', 'startups', ['funding_stage'], unique=False)
    op.create_index('ix_startups_incubator_id', 'startups', ['incubator_id'], unique=False)
    op.create_index('ix_startups_is_active', 'startups', ['is_active'], unique=False)
    op.create_index('ix_startups_name', 'startups', ['name'], unique=False)
    op.create_index('ix_startups_slug', 'startups', ['slug'], unique=False)
    op.create_table('ai_enrichments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('enrichment_type', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=255), nullable=True),
    sa.Column('input_hash', sa.String(length=255), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_enrichment_status_enum'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incubator_id', sa.UUID(), nullable=True),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('mentor_id', sa.UUID(), nullable=True),
    sa.Column('investor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('num_nonnulls(incubator_id, startup_id, mentor_id, investor_id) = 1', name='ck_ai_enrichments_exactly_one_canonical_entity'),
    sa.ForeignKeyConstraint(['incubator_id'], ['incubators.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_enrichments_incubator_id', 'ai_enrichments', ['incubator_id'], unique=False)
    op.create_index('ix_ai_enrichments_input_hash', 'ai_enrichments', ['input_hash'], unique=False)
    op.create_index('ix_ai_enrichments_investor_id', 'ai_enrichments', ['investor_id'], unique=False)
    op.create_index('ix_ai_enrichments_mentor_id', 'ai_enrichments', ['mentor_id'], unique=False)
    op.create_index('ix_ai_enrichments_model_name', 'ai_enrichments', ['model_name'], unique=False)
    op.create_index('ix_ai_enrichments_provider', 'ai_enrichments', ['provider'], unique=False)
    op.create_index('ix_ai_enrichments_startup_id', 'ai_enrichments', ['startup_id'], unique=False)
    op.create_index('ix_ai_enrichments_status', 'ai_enrichments', ['status'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('Incubator', 'Investor', 'Mentor', 'Startup', name='entity_type_enum'), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='source_status_enum'), nullable=False),
    sa.Column('incubator_id', sa.UUID(), nullable=True),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('mentor_id', sa.UUID(), nullable=True),
    sa.Column('investor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('num_nonnulls(incubator_id, startup_id, mentor_id, investor_id) = 1', name='ck_source_records_exactly_one_canonical_entity'),
    sa.ForeignKeyConstraint(['incubator_id'], ['incubators.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_records_content_hash', 'source_records', ['content_hash'], unique=False)
    op.create_index('ix_source_records_incubator_id', 'source_records', ['incubator_id'], unique=False)
    op.create_index('ix_source_records_investor_id', 'source_records', ['investor_id'], unique=False)
    op.create_index('ix_source_records_mentor_id', 'source_records', ['mentor_id'], unique=False)
    op.create_index('ix_source_records_source_name', 'source_records', ['source_name'], unique=False)
    op.create_index('ix_source_records_startup_id', 'source_records', ['startup_id'], unique=False)
    op.create_index('ix_source_records_status', 'source_records', ['status'], unique=False)
    op.create_table('pipeline_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='pipeline_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_logs_source_record_id', 'pipeline_logs', ['source_record_id'], unique=False)
    op.create_index('ix_pipeline_logs_stage', 'pipeline_logs', ['stage'], unique=False)
    op.create_index('ix_pipeline_logs_started_at', 'pipeline_logs', ['started_at'], unique=False)
    op.create_index('ix_pipeline_logs_status', 'pipeline_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_logs_status', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_started_at', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_stage', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_source_record_id', table_name='pipeline_logs')
    op.drop_table('pipeline_logs')
    op.drop_index('ix_source_records_status', table_name='source_records')
    op.drop_index('ix_source_records_startup_id', table_name='source_records')
    op.drop_index('ix_source_records_source_name', table_name='source_records')
    op.drop_index('ix_source_records_mentor_id', table_name='source_records')
    op.drop_index('ix_source_records_investor_id', table_name='source_records')
    op.drop_index('ix_source_records_incubator_id', table_name='source_records')
    op.drop_index('ix_source_records_content_hash', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index('ix_ai_enrichments_status', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_startup_id', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_provider', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_model_name', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_mentor_id', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_investor_id', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_input_hash', table_name='ai_enrichments')
    op.drop_index('ix_ai_enrichments_incubator_id', table_name='ai_enrichments')
    op.drop_table('ai_enrichments')
    op.drop_index('ix_startups_slug', table_name='startups')
    op.drop_index('ix_startups_name', table_name='startups')
    op.drop_index('ix_startups_is_active', table_name='startups')
    op.drop_index('ix_startups_incubator_id', table_name='startups')
    op.drop_index('ix_startups_funding_stage', table_name='startups')
    op.drop_table('startups')
    op.drop_index('ix_mentors_is_active', table_name='mentors')
    op.drop_index('ix_mentors_incubator_id', table_name='mentors')
    op.drop_index('ix_mentors_full_name', table_name='mentors')
    op.drop_table('mentors')
    op.drop_index('ix_incubators_slug', table_name='incubators')
    op.drop_index('ix_incubators_name', table_name='incubators')
    op.drop_index('ix_incubators_is_active', table_name='incubators')
    op.drop_index('ix_incubators_city_id', table_name='incubators')
    op.drop_table('incubators')
    op.drop_index('ix_cities_state_id', table_name='cities')
    op.drop_index('ix_cities_name', table_name='cities')
    op.drop_table('cities')
    op.drop_index('ix_states_name', table_name='states')
    op.drop_index('ix_states_code', table_name='states')
    op.drop_table('states')
    op.drop_index('ix_relationships_target_type_target_id', table_name='relationships')
    op.drop_index('ix_relationships_source_type_source_id', table_name='relationships')
    op.drop_index('ix_relationships_relationship_type', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_investors_organization', table_name='investors')
    op.drop_index('ix_investors_name', table_name='investors')
    op.drop_index('ix_investors_is_active', table_name='investors')
    op.drop_table('investors')
    # ### end Alembic commands ###
